layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    - setup-opencv

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Machine Learning
    web_url: https://github.com/topics/css
    image_url: https://imgur.com/download/H9bU3sY

  - name: EsoLangs
    web_url: https://esolangs.org
    image_url: https://imgur.com/download/G9yuSHL

  - name: Linux
    image_url: https://imgur.com/download/XAXo6Xz

  - name: Contribute to OpenSource 
    image_url: https://imgur.com/download/5DIvSnU
